apiVersion: v1
kind: Pod
metadata:
  name: auth-pod
spec:
  containers:
    - name: auth-postgres
      image: postgres:15
      ports:
        - containerPort: 5432
          hostPort: 5432
      env:
        - name: POSTGRES_DB
          value: "authdb"
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "Vengal#2025"
      volumeMounts:
        - name: auth-pgdata
          mountPath: /var/lib/postgresql/data
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"
  volumes:
    - name: auth-pgdata
      emptyDir: {}

      