apiVersion: v1
kind: Pod
metadata:
  name: conciliation-app-pod
spec:
  containers:
    - name: conciliation-service
      image: conciliation-service-app:latest
      ports:
        - containerPort: 8081
          hostPort: 8081
      env:
        - name: SPRING_APPLICATION_NAME
          value: conciliation-service
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://host.containers.internal:5433/conciliationdb
        - name: SPRING_DATASOURCE_USERNAME
          value: admin
        - name: SPRING_DATASOURCE_PASSWORD
          value: Vengal#2025
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "1"
